trigger: none
  
pr:
  branches:
    include:
    - main
    
  paths:
    include:
    - 'Application/RestaurantService/*'
    - 'Application/RestaurantServiceBDD.Test/*'
    exclude:
      - 'Application/*'

resources:
- repo: self

variables:
  imageRepo: restaurantservice
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build And Push
      inputs:
        containerRegistry: 'AzureRegistry'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Application/DockerfileRestaurant'
        tags: |
          $(tag)
          latest
    - task: DotNetCoreCLI@2
      displayName: Tests
      inputs:
        command: 'test'
        projects: '**/RestaurantService*.*[Tt]est*/*.csproj'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
        

            

- stage: Deploy
  displayName: Deploy to dev
  dependsOn: Build
  variables:
    acrsecret: 213j212iojewasdskd2oi1
    acrDevUrl: examregistry2sem.azurecr.io
    replicaNo: 1
  jobs:
    - deployment: Deploy
      displayName: Deploy to AKS
      environment: 'k8sdevNewest.app'
      pool: 
        vmImage: ubuntu-latest
      strategy:
        runOnce:
          deploy:
            steps: 
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'manifests'
                targetPath: '$(Pipeline.Workspace)/manifests'
            - task: KubernetesManifest@0
              inputs:
                action: 'createSecret'
                namespace: 'app'
                secretType: 'dockerRegistry'
                secretName: '$(acrsecret)'
                dockerRegistryEndpoint: 'AzureRegistry'
            - task: replacetokens@5
              displayName: Replace tokens
              inputs:
                rootDirectory: '$(Pipeline.Workspace)/manifests/'
                targetFiles: 'restaurantservice_deployment.yml'
                encoding: 'auto'
                tokenPattern: 'custom'
                tokenPrefix: '#'
                tokenSuffix: '#'
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                actionOnNoFiles: 'continue'
                enableTransforms: false
                enableRecursion: false
                useLegacyPattern: false
                enableTelemetry: true
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                namespace: 'app'
                manifests: |
                  $(Pipeline.Workspace)/manifests/restaurantservice_deployment.yml
                containers: '$(acrDevUrl)/$(imageRepo):$(tag)'
                imagePullSecrets: '$(acrsecret)'
       
