apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: microservice1-deployment
    labels:
        app: microservice1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: microservice1
    template: 
        metadata:
            labels:
                app: microservice1
        spec:
            containers:
            - name: k8s-demo
              image: dockerregistryexam.azurecr.io/microservice1:latest
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: dbexamregistry
---
apiVersion: v1
kind: Service
metadata:
    name: microservice1
    labels:
        app: microservice1
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 80
    selector: 
        app: microservice1
    type: LoadBalancer