// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Context;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class DbApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserService.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityInfoId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityInfoId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityInfoId = 1,
                            StreetName = "Skovledet"
                        },
                        new
                        {
                            Id = 2,
                            CityInfoId = 5,
                            StreetName = "Cphbusinessvej"
                        });
                });

            modelBuilder.Entity("UserService.Models.CityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hillerød",
                            ZipCode = "3400"
                        },
                        new
                        {
                            Id = 2,
                            City = "Fredensborg",
                            ZipCode = "3480"
                        },
                        new
                        {
                            Id = 3,
                            City = "Taastrup",
                            ZipCode = "2630"
                        },
                        new
                        {
                            Id = 4,
                            City = "Hedehusene",
                            ZipCode = "2640"
                        },
                        new
                        {
                            Id = 5,
                            City = "Charlottenlund",
                            ZipCode = "2920"
                        },
                        new
                        {
                            Id = 6,
                            City = "CityTest",
                            ZipCode = "3000"
                        });
                });

            modelBuilder.Entity("UserService.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleType = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            RoleType = "DeliveryPerson"
                        },
                        new
                        {
                            Id = 3,
                            RoleType = "RestaurantOwner"
                        });
                });

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Balance = 1000.0,
                            CreatedAt = new DateTime(2022, 12, 5, 11, 16, 8, 464, DateTimeKind.Utc).AddTicks(1904),
                            Email = "phillip.andersen1999@gmail.com",
                            FirstName = "Phillip",
                            ModifiedAt = new DateTime(2022, 12, 5, 11, 16, 8, 464, DateTimeKind.Utc).AddTicks(1906),
                            Password = "$2a$11$ICbPMppv0XMpM/5GmI9/qOsLg9x8bJtfScUPs7G3/4LBVnzOs9NcG",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Balance = 1000.0,
                            CreatedAt = new DateTime(2022, 12, 5, 11, 16, 8, 574, DateTimeKind.Utc).AddTicks(9385),
                            Email = "lukasbangstoltz@gmail.com",
                            FirstName = "Lukas",
                            ModifiedAt = new DateTime(2022, 12, 5, 11, 16, 8, 574, DateTimeKind.Utc).AddTicks(9392),
                            Password = "$2a$11$PIe18FWerkm0YH9dhRX5vu4mWDD3MCHnszyhISNhVO.H38eHV4OwG",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            Balance = 1000.0,
                            CreatedAt = new DateTime(2022, 12, 5, 11, 16, 8, 686, DateTimeKind.Utc).AddTicks(1393),
                            Email = "christofferiw@gmail.com",
                            FirstName = "Christoffer",
                            ModifiedAt = new DateTime(2022, 12, 5, 11, 16, 8, 686, DateTimeKind.Utc).AddTicks(1400),
                            Password = "$2a$11$8UpvpU.6tPDbeaO8WkNmEeh0JAzPetrJXmpe9ZOzzfa/Hfg7L9rPW",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("UserService.Models.Address", b =>
                {
                    b.HasOne("UserService.Models.CityInfo", "CityInfo")
                        .WithMany("Addresses")
                        .HasForeignKey("CityInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityInfo");
                });

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.HasOne("UserService.Models.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserService.Models.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UserService.Models.CityInfo", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("UserService.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
